import { describe, expect, it } from 'vitest';
import type { ContinuousRule } from '@guildmaster/game-protocol';
import { createGame, createRuleset, evaluateContinuousEffects } from '../src/index.js';
import { baseRulesModule } from '../src/rules/base-rules.js';
import type { RulesModule } from '../src/rules/ruleset.js';
import { testPack } from './fixtures.js';
const rule = (moduleId: string, effectId: string, sourceCardId: string, priority?: number): ContinuousRule => ({ schemaVersion: 1, moduleId, effectId, sourceCardId, duration: 'while-source-present', target: 'combat-modifier', amount: 1, ...(priority === undefined ? {} : { priority }) });
const make = (modules: RulesModule[]) => createRuleset([testPack], [baseRulesModule, ...modules]);
describe('generic continuous effect runtime', () => {
  it('evaluates a present source deterministically without state or RNG mutation', () => { const base = make([]); const state = createGame({ gameId: 'continuous', seed: 8, players: [{ id: 'p1', name: 'P1', kind: 'human' }, { id: 'p2', name: 'P2', kind: 'ai' }] }, base); const source = state.players[0]!.party[0]!.adventurerId; const module: RulesModule = { id: 'test:continuous', version: '1', getPartyLimit: (_s,_p,l) => l, onSupplyDepleted: () => 'handled', continuousRules: [rule('test:continuous', 'bonus', source, 1)] }; const ruleset = make([module]); state.rulesModules.push({ id: module.id, version: module.version }); const before = structuredClone(state); expect(evaluateContinuousEffects(state, ruleset)).toMatchObject({ status: 'ready', evaluation: { active: [{ effectId: 'bonus', amount: 1 }] } }); expect(state).toEqual(before); });
  it('expires while-source-present effects when the source leaves every active zone', () => { const ruleset = make([]); const state = createGame({ gameId: 'continuous-expire', seed: 9, players: [{ id: 'p1', name: 'P1', kind: 'human' }, { id: 'p2', name: 'P2', kind: 'ai' }] }, ruleset); const source = state.players[0]!.party[0]!.adventurerId; const module: RulesModule = { id: 'test:expiry', version: '1', getPartyLimit: (_s,_p,l) => l, onSupplyDepleted: () => 'handled', continuousRules: [rule('test:expiry', 'gone', source, 1)] }; const withRule = make([module]); state.rulesModules.push({ id: module.id, version: module.version }); expect(evaluateContinuousEffects(state, withRule)).toMatchObject({ status: 'ready', evaluation: { active: [{ effectId: 'gone' }] } }); state.players[0]!.party.shift(); state.removedCards.push(source); expect(evaluateContinuousEffects(state, withRule)).toMatchObject({ status: 'ready', evaluation: { active: [] } }); });
});
