import { describe, expect, it } from 'vitest';
import type { TeamOverflowPolicy } from '@guildmaster/game-protocol';
import { createGame, createRuleset, dispatch, envelope, evaluateTeamOverflow } from '../src/index.js';
import { baseRulesModule } from '../src/rules/base-rules.js';
import type { RulesModule } from '../src/rules/ruleset.js';
import { testPack } from './fixtures.js';

const module = (id: string, policies: readonly TeamOverflowPolicy[], limit = 1): RulesModule => ({ id, version: '1', teamOverflowPolicies: policies, getPartyLimit: (_s, _p, current) => Math.min(current, limit), onSupplyDepleted: () => 'handled' });
const policy = (moduleId: string, policyId: string, priority?: number): TeamOverflowPolicy => ({ schemaVersion: 1, moduleId, policyId, teamScope: 'player-party', mode: 'discard-oldest', reasonCode: 'OVERFLOW', ...(priority === undefined ? {} : { priority }) });
function prepared(ruleset = createRuleset([testPack], [baseRulesModule])) { const state = createGame({ gameId: 'overflow', seed: 7, players: [{ id: 'p1', name: '玩家', kind: 'human' }, { id: 'p2', name: 'AI', kind: 'ai' }], startingPlayerId: 'p1' }, ruleset); state.phase = 'action1'; const cardId = Object.values(state.cards).find((card) => card.definitionId === 'test:adventurer/a')?.id; if (!cardId) throw new Error('missing adventurer'); state.players[0]!.hand.push(cardId); return { state, cardId }; }
describe('generic team overflow policy', () => {
  it('uses the pure evaluator and dispatch policy without partial mutation', () => { const ruleset = createRuleset([testPack], [baseRulesModule, module('test:capacity', [policy('test:capacity', 'oldest', 2)], 1)]); const { state, cardId } = prepared(ruleset); const input = { schemaVersion: 1 as const, playerId: 'p1', incomingMemberId: cardId }; const evaluation = evaluateTeamOverflow(state, ruleset, input); expect(evaluation).toMatchObject({ status: 'ready', evaluation: { status: 'overflow-required' } }); if (evaluation.status === 'ready') expect(evaluation.evaluation.candidateIds[0]).toBe(state.players[0]!.party[0]!.adventurerId); const before = state.players[0]!.party[0]!.adventurerId; const result = dispatch(state, ruleset, envelope(state, 'p1', { type: 'PLAY_ADVENTURER', cardId })); expect(result.error).toBeUndefined(); expect(result.state.players[0]!.discardPile).toContain(before); expect(result.state.revision).toBe(1); });
  it('rejects ambiguous policies before mutation', () => { const ambiguous = createRuleset([testPack], [baseRulesModule, module('test:a', [policy('test:a', 'a', 2)], 1), module('test:b', [policy('test:b', 'b', 2)], 1)]); const second = prepared(ambiguous); const before = structuredClone(second.state); expect(evaluateTeamOverflow(second.state, ambiguous, { schemaVersion: 1, playerId: 'p1', incomingMemberId: second.cardId })).toMatchObject({ status: 'unsupported', reason: 'ORDER_POLICY_REQUIRED' }); expect(dispatch(second.state, ambiguous, envelope(second.state, 'p1', { type: 'PLAY_ADVENTURER', cardId: second.cardId })).state).toEqual(before); });
});
