import type { EffectCapabilityMatrix } from './schema.js';

/** Current implementation evidence, not a promise that provisional cards can load. */
export const baseProvisionalEffectCapabilityMatrix: EffectCapabilityMatrix = {
  schemaVersion: 1, contentScope: 'base:provisional', generatedFor: 'provisional-gap-analysis',
  capabilities: [
    { id: 'card-movement/player-draw-rebuild', category: 'card-movement', status: 'supported', summary: '個人抽牌途中牌庫耗盡且仍需抽牌時，以棄牌堆重建牌庫。', engineEvidence: ['packages/game-engine/src/engine/draw.ts', 'packages/game-engine/test/draw.test.ts'] },
    { id: 'card-movement/reveal-top-without-rebuild', category: 'card-movement', status: 'supported', summary: '展示個人牌庫頂只讀取現有牌庫，不觸發洗牌。', candidateDefinitionIds: ['base:adventurer/adventurer-01'], engineEvidence: ['packages/game-engine/src/engine/draw.ts#revealTopCards', 'packages/game-engine/test/draw.test.ts'] },
    { id: 'card-movement/generic-zone-transfer', category: 'card-movement', status: 'supported', summary: '以可序列化 location selector 在玩家區、隊伍、裝備、移除區與 module zone 原子移動、棄置或移除卡片。', engineEvidence: ['packages/game-engine/src/effects/movement.ts', 'packages/game-engine/test/effects.test.ts'] },
    { id: 'supply/refill-and-depletion-event', category: 'supply', status: 'missing-generic-capability', summary: '既有基礎公共列可補牌，供應牌庫抽空會產生正式事件。', engineEvidence: ['packages/game-engine/src/engine/supply.ts', 'packages/game-engine/test/faq-boundaries.test.ts'], gapOrConstraint: '目前 supplyZones 與列長度寫死為基礎版四個 zone；擴充或 module zones 不能宣告自己的供應列。', recommendedNextStep: '將供應列設定移至可版本化 Rules Module/Content Pack 設定，再保留既有抽空事件契約。' },
    { id: 'supply/base-composition-by-copy-count', category: 'supply', status: 'blocked-by-rule-exception', summary: '依正確逐種份數組成物資與魔物供應牌庫。', candidateDefinitionIds: ['base:resource/resource-01', 'base:monster/monster-01'], engineEvidence: ['packages/content-base/src/provisional/base-provisional-catalog.ts', 'docs/26-基礎版Provisional例外清單.md'], gapOrConstraint: '28 種物資與 14 種魔物的逐種份數尚無可確認官方來源；不可由總數反推或建立非官方 supply composition policy。', recommendedNextStep: '取得可合法稽核的逐種份數官方資料後才解除。' },
    { id: 'supply/refresh-public-row', category: 'supply', status: 'missing-generic-capability', summary: '依卡片效果或規則刷新／重排公開供應列。', engineEvidence: ['packages/game-engine/src/engine/supply.ts'], gapOrConstraint: '只有休息時補列，沒有 refreshMarket command/effect 與選擇流程。', recommendedNextStep: '以 selector + moveCard primitive 加入明確 refresh policy。' },
    { id: 'supply/depletion-resolution', category: 'supply', status: 'blocked-by-rule-exception', summary: '基礎版供應牌庫耗盡後的正式後續處理。', engineEvidence: ['packages/game-engine/src/rules/base-rules.ts', 'packages/game-engine/src/engine/dispatch.ts'], gapOrConstraint: '現況在本次休息結束後設定 pendingOfficialRuling 並凍結後續 Command；這是安全暫停，非官方結果。', recommendedNextStep: '取得官方裁定前維持 pendingOfficialRuling，不自行結束、補牌或繼續。' },
    { id: 'combat/basic-target-and-prefix-party', category: 'combat', status: 'supported', summary: '可選取可討伐 target，依隊伍前綴累積戰力並將參與者移出隊伍。', engineEvidence: ['packages/game-engine/src/engine/dispatch.ts#attackTarget', 'packages/game-engine/src/queries/legal-commands.ts'] },
    { id: 'combat/generic-reward-and-combat-modifier', category: 'combat', status: 'missing-generic-capability', summary: '討伐獎勵、條件戰力修正、限制與替代討伐結果。', candidateDefinitionIds: ['base:monster/monster-01', 'base:boss/boss-01'], engineEvidence: ['packages/game-engine/src/engine/dispatch.ts#attackTarget'], gapOrConstraint: '討伐只會將目標送入棄牌堆並更新歷史；沒有可資料驅動的 reward／modifyCombatPower／replaceCombatRule。', recommendedNextStep: '先實作通用 effect queue，再把獎勵接在 ENEMY_DEFEATED 時序。' },
    { id: 'combat/multi-target-encounter-resolution', category: 'combat', status: 'missing-generic-capability', summary: '同時存在的目標、附屬卡與多部位 encounter 的結算。', engineEvidence: ['packages/game-protocol/src/state.ts#EnemyTargetState', 'packages/game-engine/src/engine/create-game.ts'], gapOrConstraint: 'Snapshot model 已可保存 targets、attachments、health 與 encounters，但 reducer 沒有建立、傷害或聚合結算 primitive。', recommendedNextStep: '建立 createEncounter/createEnemyTarget/damageEnemyTarget/defeatEnemyTarget primitives。' },
    { id: 'party-and-equipment/dynamic-party-limit', category: 'party-and-equipment', status: 'supported', summary: '隊伍上限由 Rules Module 動態計算，未寫死為五人。', engineEvidence: ['packages/game-engine/src/rules/ruleset.ts#getPartyLimit', 'packages/game-engine/src/engine/dispatch.ts#playAdventurer'] },
    { id: 'party-and-equipment/equipment-slot-and-rest-play-area', category: 'party-and-equipment', status: 'supported', summary: '每位隊員可替換一件裝備；道具進使用區並於休息棄置。', engineEvidence: ['packages/game-engine/src/engine/dispatch.ts#equipItem', 'packages/game-engine/src/engine/dispatch.ts#finishRest', 'packages/game-engine/test/faq-boundaries.test.ts'] },
    { id: 'party-and-equipment/generic-eligibility-and-overflow-policy', category: 'party-and-equipment', status: 'missing-generic-capability', summary: '職業／卡面限制的裝備資格，以及隊伍上限變動時可設定的溢出處理。', candidateDefinitionIds: ['base:resource/resource-01'], engineEvidence: ['packages/game-engine/src/engine/dispatch.ts#equipItem', 'packages/game-engine/src/rules/ruleset.ts'], gapOrConstraint: '目前 equip 只檢查卡牌種類；隊伍滿時是 reducer 內固定左側離隊，沒有 policy／資格 selector。', recommendedNextStep: '把 eligibility 與 overflow policy 放進 Rules Module/Effect AST，而非卡牌專用分支。' },
    { id: 'randomness-and-visibility/deterministic-shuffle', category: 'randomness-and-visibility', status: 'supported', summary: '洗牌使用權威 rngState，可寫入 Snapshot 並重播。', engineEvidence: ['packages/game-engine/src/ports/random.ts', 'packages/game-protocol/src/state.ts'] },
    { id: 'randomness-and-visibility/dice-and-random-choice', category: 'randomness-and-visibility', status: 'missing-generic-capability', summary: '骰子與可稽核的隨機結果，以及由效果要求的隨機選擇。', engineEvidence: ['packages/game-engine/src/ports/random.ts'], gapOrConstraint: '目前只有 shuffle；沒有 roll、結果事件或效果 continuation。', recommendedNextStep: '在 Effect AST 中加入注入式 RNG primitive 與序列化結果事件。' },
    { id: 'randomness-and-visibility/player-view-redaction', category: 'randomness-and-visibility', status: 'supported', summary: 'PlayerView 隱藏其他玩家手牌與個人牌庫順序。', engineEvidence: ['packages/game-engine/src/queries/player-view.ts', 'packages/game-engine/test/player-view.test.ts'] },
    { id: 'randomness-and-visibility/pending-choice-and-counter-consent', category: 'randomness-and-visibility', status: 'not-in-MVP-yet', summary: '玩家選擇、隱藏／公開計數資源與全體同意公開流程。', engineEvidence: ['packages/game-protocol/src/state.ts#PlayerCounterState', 'docs/04-卡牌效果與時序.md'], gapOrConstraint: '資料模型可保存 counters，但沒有 choice command、consent command、事件或 viewer-aware counter projection。', recommendedNextStep: '在擴充需要前，以版本化 pending choice state 與 visibility policy 實作。' },
    { id: 'timing-and-effects/phase-and-rest-lifecycle', category: 'timing-and-effects', status: 'supported', summary: 'action1、combat、action2、purchase、rest 的命令式流程與休息清理可重播。', engineEvidence: ['packages/game-engine/src/engine/dispatch.ts#endPhase', 'packages/game-engine/src/engine/dispatch.ts#finishRest'] },
    { id: 'timing-and-effects/declarative-effect-ast', category: 'timing-and-effects', status: 'supported', summary: '可序列化、版本化的通用 Effect AST，具 sequence、conditional、choice、random、move、draw、discard、remove 與 modify-value primitives。', engineEvidence: ['packages/game-protocol/src/effects.ts', 'packages/game-engine/src/effects/executor.ts', 'packages/game-engine/test/effects.test.ts'] },
    { id: 'timing-and-effects/triggers-duration-and-replacements', category: 'timing-and-effects', status: 'missing-generic-capability', summary: '事件觸發、持續效果、替代效果與可中斷的時序佇列。', candidateDefinitionIds: ['base:boss/boss-01', 'base:helper/helper-01'], engineEvidence: ['packages/game-protocol/src/commands.ts', 'packages/game-engine/src/engine/dispatch.ts'], gapOrConstraint: 'DomainEvent 僅是紀錄，沒有 trigger registry、effect queue 或 replacement resolver。', recommendedNextStep: '先建立純 reducer 的 lifecycle hook/queue contract，再由 Rules Module 註冊通用 handler。' },
    { id: 'bonds-endgame-and-scoring/end-condition-and-score-hooks', category: 'bonds-endgame-and-scoring', status: 'supported', summary: 'Rules Module 可提供可插拔終局條件與分數 contribution。', engineEvidence: ['packages/game-engine/src/rules/ruleset.ts', 'packages/game-engine/src/queries/scoring.ts', 'packages/game-engine/test/contracts.test.ts'] },
    { id: 'bonds-endgame-and-scoring/generic-bond-conditions', category: 'bonds-endgame-and-scoring', status: 'missing-generic-capability', summary: '依羈絆卡資料評估職業、卡牌、位置與其他複合條件。', candidateDefinitionIds: ['base:bond/bond-01'], engineEvidence: ['packages/game-engine/src/engine/dispatch.ts#maybeCompleteBonds', 'packages/game-protocol/src/cards.ts'], gapOrConstraint: '現況 bond 只有 requiredBosses 數字，無法承載 provisional 羈絆條件。', recommendedNextStep: '在 Effect AST 之外建立可序列化 BondCondition schema 與 evaluator。' },
    { id: 'bonds-endgame-and-scoring/vol1-ranking-and-hp', category: 'bonds-endgame-and-scoring', status: 'not-in-MVP-yet', summary: 'Vol.1 的 HP、排名、同分平均與多部位究極魔神計分。', engineEvidence: ['docs/10-第一擴充Vol1規則.md', 'packages/game-protocol/src/state.ts'], gapOrConstraint: '完整目標模型預留 counter/target 狀態，但 Vol.1 Rules Module 與排名 policy 不在基礎版 MVP 範圍。', recommendedNextStep: '等第一擴充啟用時，以獨立 Rules Module 和 scoring policy 實作。' }
  ]
};
