import type { EffectCapabilityMatrix } from './schema.js';

/** Current implementation evidence, not a promise that provisional cards can load. */
export const baseProvisionalEffectCapabilityMatrix: EffectCapabilityMatrix = {
  schemaVersion: 1, contentScope: 'base:provisional', generatedFor: 'provisional-gap-analysis',
  capabilities: [
    { id: 'card-movement/player-draw-rebuild', category: 'card-movement', status: 'supported', summary: '個人抽牌途中牌庫耗盡且仍需抽牌時，以棄牌堆重建牌庫。', engineEvidence: ['packages/game-engine/src/engine/draw.ts', 'packages/game-engine/test/draw.test.ts'] },
    { id: 'card-movement/reveal-top-without-rebuild', category: 'card-movement', status: 'supported', summary: '展示個人牌庫頂只讀取現有牌庫，不觸發洗牌。', candidateDefinitionIds: ['base:adventurer/adventurer-01'], engineEvidence: ['packages/game-engine/src/engine/draw.ts#revealTopCards', 'packages/game-engine/test/draw.test.ts'] },
    { id: 'card-movement/generic-zone-transfer', category: 'card-movement', status: 'supported', summary: '以可序列化 location selector 在玩家區、隊伍、裝備、移除區與 module zone 原子移動、棄置或移除卡片。', engineEvidence: ['packages/game-engine/src/effects/movement.ts', 'packages/game-engine/test/effects.test.ts'] },
    { id: 'supply/refill-and-depletion-event', category: 'supply', status: 'supported', summary: 'Rules Module JSON-only configuration 定義供應 deck／row 配對與 refill-to-target evaluation；既有耗盡事件保留。', engineEvidence: ['packages/game-protocol/src/supply.ts', 'packages/game-engine/src/rules/supply-row-evaluator.ts', 'packages/game-engine/src/engine/supply.ts'] },
    { id: 'supply/base-composition-by-copy-count', category: 'supply', status: 'blocked-by-rule-exception', summary: '依正確逐種份數組成物資與魔物供應牌庫。', candidateDefinitionIds: ['base:resource/resource-01', 'base:monster/monster-01'], engineEvidence: ['packages/content-base/src/provisional/base-provisional-catalog.ts', 'docs/26-基礎版Provisional例外清單.md'], gapOrConstraint: '28 種物資與 14 種魔物的逐種份數尚無可確認官方來源；不可由總數反推或建立非官方 supply composition policy。', recommendedNextStep: '取得可合法稽核的逐種份數官方資料後才解除。' },
    { id: 'supply/refresh-public-row', category: 'supply', status: 'supported', summary: 'Rules Module JSON-only refresh policy 與 Effect AST 可將固定公開列卡片依明確 destination/order 移動，並選擇性補列；未載入任何卡牌或官方 base refresh policy。', engineEvidence: ['packages/game-protocol/src/supply.ts', 'packages/game-engine/src/rules/supply-row-refresh-evaluator.ts', 'packages/game-engine/test/supply-row-refresh.test.ts'] },
    { id: 'supply/depletion-resolution', category: 'supply', status: 'blocked-by-rule-exception', summary: '基礎版供應牌庫耗盡後的正式後續處理。', engineEvidence: ['packages/game-engine/src/rules/base-rules.ts', 'packages/game-engine/src/engine/dispatch.ts'], gapOrConstraint: '現況在本次休息結束後設定 pendingOfficialRuling 並凍結後續 Command；這是安全暫停，非官方結果。', recommendedNextStep: '取得官方裁定前維持 pendingOfficialRuling，不自行結束、補牌或繼續。' },
    { id: 'combat/basic-target-and-prefix-party', category: 'combat', status: 'supported', summary: '可選取可討伐 target，依隊伍前綴累積戰力並將參與者移出隊伍。', engineEvidence: ['packages/game-engine/src/engine/dispatch.ts#attackTarget', 'packages/game-engine/src/queries/legal-commands.ts'] },
    { id: 'combat/data-driven-reward', category: 'combat', status: 'supported', summary: 'ENEMY_DEFEATED lifecycle boundary 可執行資料驅動的抽牌、暫時戰力／購買力與 counter 討伐獎勵。', candidateDefinitionIds: ['base:monster/monster-01', 'base:boss/boss-01'], engineEvidence: ['packages/game-protocol/src/effects.ts', 'packages/game-engine/src/engine/dispatch.ts#attackTarget', 'packages/game-engine/test/lifecycle.test.ts'] },
    { id: 'combat/generic-combat-modifier-and-replacement', category: 'combat', status: 'supported', summary: 'Rules Module 可用 JSON-only conditions 註冊戰力修正、討伐限制與 defeat/remove-target replacement；query 與 dispatch 共用確定性 evaluation。', candidateDefinitionIds: ['base:monster/monster-01', 'base:boss/boss-01'], engineEvidence: ['packages/game-protocol/src/combat.ts', 'packages/game-engine/src/rules/combat-evaluator.ts', 'packages/game-engine/test/combat-evaluator.test.ts'] },
    { id: 'combat/multi-target-encounter-resolution', category: 'combat', status: 'missing-generic-capability', summary: '同時存在的目標、附屬卡與多部位 encounter 的結算。', engineEvidence: ['packages/game-protocol/src/state.ts#EnemyTargetState', 'packages/game-engine/src/engine/create-game.ts'], gapOrConstraint: 'Snapshot model 已可保存 targets、attachments、health 與 encounters，但 reducer 沒有建立、傷害或聚合結算 primitive。', recommendedNextStep: '建立 createEncounter/createEnemyTarget/damageEnemyTarget/defeatEnemyTarget primitives。' },
    { id: 'party-and-equipment/dynamic-party-limit', category: 'party-and-equipment', status: 'supported', summary: '隊伍上限由 Rules Module 動態計算，未寫死為五人。', engineEvidence: ['packages/game-engine/src/rules/ruleset.ts#getPartyLimit', 'packages/game-engine/src/engine/dispatch.ts#playAdventurer'] },
    { id: 'party-and-equipment/equipment-slot-and-rest-play-area', category: 'party-and-equipment', status: 'supported', summary: '每位隊員可替換一件裝備；道具進使用區並於休息棄置。', engineEvidence: ['packages/game-engine/src/engine/dispatch.ts#equipItem', 'packages/game-engine/src/engine/dispatch.ts#finishRest', 'packages/game-engine/test/faq-boundaries.test.ts'] },
    { id: 'party-and-equipment/generic-equipment-eligibility', category: 'party-and-equipment', status: 'supported', summary: 'Rules Module 可用 JSON-only conditions、明確 priority 與結構化 rejection reason 評估裝備資格；legal query 與 EQUIP_ITEM dispatch 共用純 evaluator。', engineEvidence: ['packages/game-protocol/src/equipment.ts', 'packages/game-engine/src/rules/equipment-eligibility-evaluator.ts', 'packages/game-engine/test/equipment-eligibility-evaluator.test.ts'] },
    { id: 'party-and-equipment/generic-team-overflow-policy', category: 'party-and-equipment', status: 'supported', summary: 'Rules Module 可用 JSON-only capacity overflow policy、explicit priority 與 automatic/player-choice resolution 解決隊伍超額；dispatch、event payload 與 evaluator 共用固定 candidate IDs，choice 可跨 Snapshot 恢復。', engineEvidence: ['packages/game-protocol/src/team-overflow.ts', 'packages/game-engine/src/rules/team-overflow-evaluator.ts', 'packages/game-engine/test/team-overflow.test.ts'] },
    { id: 'party-and-equipment/party-overflow-policy', category: 'party-and-equipment', status: 'missing-generic-capability', summary: '隊伍上限變動時可設定的溢出處理。', engineEvidence: ['packages/game-engine/src/engine/dispatch.ts#playAdventurer', 'packages/game-engine/src/rules/ruleset.ts'], gapOrConstraint: '目前隊伍滿時仍是 reducer 內固定左側離隊，沒有可配置 overflow policy。', recommendedNextStep: '把 overflow policy 放進 Rules Module/Effect AST，而非卡牌專用分支。' },
    { id: 'randomness-and-visibility/deterministic-shuffle', category: 'randomness-and-visibility', status: 'supported', summary: '洗牌使用權威 rngState，可寫入 Snapshot 並重播。', engineEvidence: ['packages/game-engine/src/ports/random.ts', 'packages/game-protocol/src/state.ts'] },
    { id: 'randomness-and-visibility/dice-and-random-choice', category: 'randomness-and-visibility', status: 'missing-generic-capability', summary: 'Effect AST 已支援可稽核 deterministic random outcome；通用骰子契約仍未實作。', engineEvidence: ['packages/game-engine/src/ports/random.ts', 'packages/game-engine/src/effects/executor.ts', 'packages/game-engine/test/effects.test.ts'], gapOrConstraint: 'random choice 與結果事件已有基礎，但沒有帶面數／結果語意的通用 roll primitive。', recommendedNextStep: '有已驗證卡牌需求時再加入版本化 dice primitive，不以卡名分支。' },
    { id: 'randomness-and-visibility/player-view-redaction', category: 'randomness-and-visibility', status: 'supported', summary: 'PlayerView 隱藏其他玩家手牌與個人牌庫順序。', engineEvidence: ['packages/game-engine/src/queries/player-view.ts', 'packages/game-engine/test/player-view.test.ts'] },
    { id: 'randomness-and-visibility/pending-choice-and-counter-consent', category: 'randomness-and-visibility', status: 'not-in-MVP-yet', summary: '版本化 pending choice 與 resume command 已實作；隱藏／公開計數資源的全體同意流程尚未實作。', engineEvidence: ['packages/game-protocol/src/effects.ts', 'packages/game-engine/src/effects/executor.ts', 'packages/game-engine/test/effects.test.ts'], gapOrConstraint: 'choice 可 Snapshot round-trip，但沒有 consent command、事件或 viewer-aware counter projection。', recommendedNextStep: '等擴充需要時，以 visibility policy 補 counter consent，不改既有 choice contract。' },
    { id: 'timing-and-effects/phase-and-rest-lifecycle', category: 'timing-and-effects', status: 'supported', summary: 'action1、combat、action2、purchase、rest 的命令式流程與休息清理可重播。', engineEvidence: ['packages/game-engine/src/engine/dispatch.ts#endPhase', 'packages/game-engine/src/engine/dispatch.ts#finishRest'] },
    { id: 'timing-and-effects/declarative-effect-ast', category: 'timing-and-effects', status: 'supported', summary: '可序列化、版本化的通用 Effect AST，具 sequence、conditional、choice、random、move、draw、discard、remove 與 modify-value primitives。', engineEvidence: ['packages/game-protocol/src/effects.ts', 'packages/game-engine/src/effects/executor.ts', 'packages/game-engine/test/effects.test.ts'] },
    { id: 'timing-and-effects/lifecycle-registry-and-dispatch', category: 'timing-and-effects', status: 'supported', summary: 'Rules Module 可註冊可序列化 lifecycle hooks；command-before 與三種 post-command choice 可跨 Snapshot 從精確 fact/boundary cursor 恢復，不重複 reducer、facts、hooks、events 或 RNG，後段失敗回到 command 起點。', candidateDefinitionIds: ['base:boss/boss-01', 'base:helper/helper-01'], engineEvidence: ['packages/game-protocol/src/lifecycle.ts', 'packages/game-engine/src/engine/post-command-pipeline.ts', 'packages/game-engine/test/post-command-pipeline.test.ts'] },
    { id: 'timing-and-effects/continuous-card-effects', category: 'timing-and-effects', status: 'missing-generic-capability', summary: 'continuous hook 目前只提供可驗證 evaluation boundary，不執行正式或 provisional 卡牌持續效果。', candidateDefinitionIds: ['base:boss/boss-01', 'base:helper/helper-01'], engineEvidence: ['packages/game-engine/src/effects/lifecycle-dispatcher.ts', 'packages/game-engine/test/lifecycle.test.ts'], gapOrConstraint: '尚未定義 duration/source-presence 的通用套用與撤銷語意，也未載入卡牌內容。', recommendedNextStep: '待個別官方效果與時序可稽核後，另做 continuous evaluation/apply contract。' },
    { id: 'bonds-endgame-and-scoring/end-condition-and-score-hooks', category: 'bonds-endgame-and-scoring', status: 'supported', summary: 'Rules Module 可提供可插拔終局條件與分數 contribution。', engineEvidence: ['packages/game-engine/src/rules/ruleset.ts', 'packages/game-engine/src/queries/scoring.ts', 'packages/game-engine/test/contracts.test.ts'] },
    { id: 'bonds-endgame-and-scoring/generic-bond-conditions', category: 'bonds-endgame-and-scoring', status: 'missing-generic-capability', summary: '依羈絆卡資料評估職業、卡牌、位置與其他複合條件。', candidateDefinitionIds: ['base:bond/bond-01'], engineEvidence: ['packages/game-engine/src/engine/dispatch.ts#maybeCompleteBonds', 'packages/game-protocol/src/cards.ts'], gapOrConstraint: '現況 bond 只有 requiredBosses 數字，無法承載 provisional 羈絆條件。', recommendedNextStep: '在 Effect AST 之外建立可序列化 BondCondition schema 與 evaluator。' },
    { id: 'bonds-endgame-and-scoring/vol1-ranking-and-hp', category: 'bonds-endgame-and-scoring', status: 'not-in-MVP-yet', summary: 'Vol.1 的 HP、排名、同分平均與多部位究極魔神計分。', engineEvidence: ['docs/10-第一擴充Vol1規則.md', 'packages/game-protocol/src/state.ts'], gapOrConstraint: '完整目標模型預留 counter/target 狀態，但 Vol.1 Rules Module 與排名 policy 不在基礎版 MVP 範圍。', recommendedNextStep: '等第一擴充啟用時，以獨立 Rules Module 和 scoring policy 實作。' }
  ]
};
