import type { EffectCapabilityMatrix } from './schema.js';

/** Current implementation evidence, not a promise that provisional cards can load. */
export const baseProvisionalEffectCapabilityMatrix: EffectCapabilityMatrix = {
  schemaVersion: 1, contentScope: 'base:provisional', generatedFor: 'provisional-gap-analysis',
  capabilities: [
    { id: 'card-movement/player-draw-rebuild', category: 'card-movement', status: 'supported', summary: '個人抽牌途中牌庫耗盡且仍需抽牌時，以棄牌堆重建牌庫。', engineEvidence: ['packages/game-engine/src/engine/draw.ts', 'packages/game-engine/test/draw.test.ts'] },
    { id: 'card-movement/reveal-top-without-rebuild', category: 'card-movement', status: 'supported', summary: '展示個人牌庫頂只讀取現有牌庫，不觸發洗牌。', candidateDefinitionIds: ['base:adventurer/adventurer-01'], engineEvidence: ['packages/game-engine/src/engine/draw.ts#revealTopCards', 'packages/game-engine/test/draw.test.ts'] },
    { id: 'card-movement/generic-zone-transfer', category: 'card-movement', status: 'supported', summary: '以可序列化 location selector 在玩家區、隊伍、裝備、移除區與 module zone 原子移動、棄置或移除卡片。', engineEvidence: ['packages/game-engine/src/effects/movement.ts', 'packages/game-engine/test/effects.test.ts'] },
    { id: 'supply/refill-and-depletion-event', category: 'supply', status: 'supported', summary: 'Rules Module JSON-only configuration 定義供應 deck／row 配對與 refill-to-target evaluation；既有耗盡事件保留。', engineEvidence: ['packages/game-protocol/src/supply.ts', 'packages/game-engine/src/rules/supply-row-evaluator.ts', 'packages/game-engine/src/engine/supply.ts'] },
    { id: 'supply/base-composition-by-copy-count', category: 'supply', status: 'supported', summary: 'Content Pack 對自身數位組成負責；其他逐種類張數可保留為非阻擋 metadata，循環錨點依 2026-07-31 project policy 固定為 3 張且不冒充官方配比。', candidateDefinitionIds: ['base:resource/resource-01', 'base:monster/monster-01'], engineEvidence: ['packages/content-base/src/provisional/base-provisional-catalog.ts', 'packages/game-engine/src/rules/supply-continuity-evaluator.ts', 'packages/game-engine/test/supply-continuity-policy.test.ts'] },
    { id: 'supply/refresh-public-row', category: 'supply', status: 'supported', summary: 'Rules Module JSON-only refresh policy 與 Effect AST 可將固定公開列卡片依明確 destination/order 移動，並選擇性補列；未載入任何卡牌或官方 base refresh policy。', engineEvidence: ['packages/game-protocol/src/supply.ts', 'packages/game-engine/src/rules/supply-row-refresh-evaluator.ts', 'packages/game-engine/test/supply-row-refresh.test.ts'] },
    { id: 'supply/depletion-resolution', category: 'supply', status: 'supported', summary: '核准的基礎版 project policy 允許冒險者／物資公開列縮減至空並繼續；魔物供應以 3 張循環錨點維持恆為 3，不產生 monster depletion 或 pending ruling。', engineEvidence: ['packages/game-engine/src/rules/base-rules.ts', 'packages/game-engine/src/rules/supply-continuity-evaluator.ts', 'packages/game-engine/src/engine/supply.ts', 'packages/game-engine/test/supply-continuity-policy.test.ts'] },
    { id: 'combat/basic-target-and-prefix-party', category: 'combat', status: 'supported', summary: '可選取可討伐 target，依隊伍前綴累積戰力並將參與者移出隊伍。', engineEvidence: ['packages/game-engine/src/engine/dispatch.ts#attackTarget', 'packages/game-engine/src/queries/legal-commands.ts'] },
    { id: 'combat/data-driven-reward', category: 'combat', status: 'supported', summary: 'Rules Module JSON-only CombatRewardPolicy 以固定 target／encounter evaluation 和 explicit priority 執行 Effect AST；choice 可跨 Snapshot 依 policy cursor 恢復，不重複 reducer、events 或 RNG，未載入任何卡牌獎勵 policy。', candidateDefinitionIds: ['base:monster/monster-01', 'base:boss/boss-01'], engineEvidence: ['packages/game-protocol/src/combat-reward.ts', 'packages/game-engine/src/engine/combat-reward-pipeline.ts', 'packages/game-engine/test/combat-reward-evaluator.test.ts'] },
    { id: 'combat/generic-combat-modifier-and-replacement', category: 'combat', status: 'supported', summary: 'Rules Module 可用 JSON-only conditions 註冊戰力修正、討伐限制與 defeat/remove-target replacement；query 與 dispatch 共用確定性 evaluation。', candidateDefinitionIds: ['base:monster/monster-01', 'base:boss/boss-01'], engineEvidence: ['packages/game-protocol/src/combat.ts', 'packages/game-engine/src/rules/combat-evaluator.ts', 'packages/game-engine/test/combat-evaluator.test.ts'] },
    { id: 'combat/multi-target-encounter-resolution', category: 'combat', status: 'supported', summary: 'Rules Module JSON-only encounter 與 attack-resolution policies 可原子建立多目標、附屬卡、health damage、remove/defeat/finish、completion 與 disposition；health target 的 ATTACK_TARGET query／dispatch 共用 combat、party-prefix、fixed damage 與 lethal outcome evaluation，Snapshot/choice/consent/lifecycle resume 不重跑 mutation 或 RNG。未載入任何正式或 provisional 多部位內容。', engineEvidence: ['packages/game-protocol/src/encounter.ts', 'packages/game-protocol/src/attack-resolution.ts', 'packages/game-engine/src/rules/encounter-resolution-evaluator.ts', 'packages/game-engine/src/rules/attack-resolution-evaluator.ts', 'packages/game-engine/src/engine/encounter-resolution.ts', 'packages/game-engine/test/encounter-resolution.test.ts', 'packages/game-engine/test/attack-resolution-evaluator.test.ts'] },
    { id: 'party-and-equipment/dynamic-party-limit', category: 'party-and-equipment', status: 'supported', summary: '隊伍上限由 Rules Module 動態計算，未寫死為五人。', engineEvidence: ['packages/game-engine/src/rules/ruleset.ts#getPartyLimit', 'packages/game-engine/src/engine/dispatch.ts#playAdventurer'] },
    { id: 'party-and-equipment/equipment-slot-and-rest-play-area', category: 'party-and-equipment', status: 'supported', summary: '每位隊員可替換一件裝備；道具進使用區並於休息棄置。', engineEvidence: ['packages/game-engine/src/engine/dispatch.ts#equipItem', 'packages/game-engine/src/engine/dispatch.ts#finishRest', 'packages/game-engine/test/faq-boundaries.test.ts'] },
    { id: 'party-and-equipment/generic-equipment-eligibility', category: 'party-and-equipment', status: 'supported', summary: 'Rules Module 可用 JSON-only conditions、明確 priority 與結構化 rejection reason 評估裝備資格；legal query 與 EQUIP_ITEM dispatch 共用純 evaluator。', engineEvidence: ['packages/game-protocol/src/equipment.ts', 'packages/game-engine/src/rules/equipment-eligibility-evaluator.ts', 'packages/game-engine/test/equipment-eligibility-evaluator.test.ts'] },
    { id: 'party-and-equipment/wearer-conditioned-combat-power', category: 'party-and-equipment', status: 'supported', summary: 'Rules Module 可依裝備定義、配戴者定義／tag、phase 或 counter，以 JSON-only conditions 修正該隊伍前綴的戰力；legal query 與 authoritative attack dispatch 共用純 evaluator。候選物資 02 的確切加成數值仍缺證據，因此未載入其個別規則。', candidateDefinitionIds: ['base:resource/resource-02'], engineEvidence: ['packages/game-protocol/src/equipment.ts', 'packages/game-engine/src/rules/equipment-combat-modifier-evaluator.ts', 'packages/game-engine/src/rules/combat-evaluator.ts', 'packages/game-engine/test/equipment-combat-modifier-evaluator.test.ts'] },
    { id: 'party-and-equipment/generic-team-overflow-policy', category: 'party-and-equipment', status: 'supported', summary: 'Rules Module 可用 JSON-only capacity overflow policy、explicit priority 與 automatic/player-choice resolution 解決隊伍超額；dispatch、event payload 與 evaluator 共用固定 candidate IDs，choice 可跨 Snapshot 恢復。', engineEvidence: ['packages/game-protocol/src/team-overflow.ts', 'packages/game-engine/src/rules/team-overflow-evaluator.ts', 'packages/game-engine/test/team-overflow.test.ts'] },
    { id: 'randomness-and-visibility/deterministic-shuffle', category: 'randomness-and-visibility', status: 'supported', summary: '洗牌使用權威 rngState，可寫入 Snapshot 並重播。', engineEvidence: ['packages/game-engine/src/ports/random.ts', 'packages/game-protocol/src/state.ts'] },
    { id: 'randomness-and-visibility/dice-and-random-choice', category: 'randomness-and-visibility', status: 'supported', summary: 'Rules Module JSON-only dice definition 與 roll-die Effect AST 以既有權威 RNG 產生固定 face、structured DIE_ROLLED event 與可重播 outcome；未載入卡牌骰子內容。', engineEvidence: ['packages/game-protocol/src/dice.ts', 'packages/game-engine/src/rules/dice-evaluator.ts', 'packages/game-engine/test/dice-evaluator.test.ts'] },
    { id: 'randomness-and-visibility/player-view-redaction', category: 'randomness-and-visibility', status: 'supported', summary: 'PlayerView 隱藏其他玩家手牌與個人牌庫順序。', engineEvidence: ['packages/game-engine/src/queries/player-view.ts', 'packages/game-engine/test/player-view.test.ts'] },
    { id: 'randomness-and-visibility/pending-choice-and-counter-consent', category: 'randomness-and-visibility', status: 'supported', summary: '版本化 pending choice 與獨立多 actor counter consent suspension 可跨 Snapshot 恢復；Rules Module JSON-only policy、純 evaluator、專用 Commands、structured reason/event 與 PlayerView projection 在全體接受後才將 counter 公開。未載入 Vol.1 HP 或卡牌時序。', engineEvidence: ['packages/game-protocol/src/counter-consent.ts', 'packages/game-engine/src/rules/counter-consent-evaluator.ts', 'packages/game-engine/test/counter-consent.test.ts'] },
    { id: 'timing-and-effects/phase-and-rest-lifecycle', category: 'timing-and-effects', status: 'supported', summary: 'action1、combat、action2、purchase、rest 的命令式流程與休息清理可重播。', engineEvidence: ['packages/game-engine/src/engine/dispatch.ts#endPhase', 'packages/game-engine/src/engine/dispatch.ts#finishRest'] },
    { id: 'timing-and-effects/declarative-effect-ast', category: 'timing-and-effects', status: 'supported', summary: '可序列化、版本化的通用 Effect AST，具 sequence、conditional、choice、random、move、draw、discard、remove 與 modify-value primitives。', engineEvidence: ['packages/game-protocol/src/effects.ts', 'packages/game-engine/src/effects/executor.ts', 'packages/game-engine/test/effects.test.ts'] },
    { id: 'timing-and-effects/lifecycle-registry-and-dispatch', category: 'timing-and-effects', status: 'supported', summary: 'Rules Module 可註冊可序列化 lifecycle hooks；command-before 與三種 post-command choice 可跨 Snapshot 從精確 fact/boundary cursor 恢復，不重複 reducer、facts、hooks、events 或 RNG，後段失敗回到 command 起點。', candidateDefinitionIds: ['base:boss/boss-01', 'base:helper/helper-01'], engineEvidence: ['packages/game-protocol/src/lifecycle.ts', 'packages/game-engine/src/engine/post-command-pipeline.ts', 'packages/game-engine/test/post-command-pipeline.test.ts'] },
    { id: 'timing-and-effects/continuous-card-effects', category: 'timing-and-effects', status: 'supported', summary: 'JSON-only continuous runtime 以 source presence、duration 與 explicit priority 導出可重播 evaluation，不直接累加 GameState；未載入任何卡牌效果。', engineEvidence: ['packages/game-protocol/src/continuous.ts', 'packages/game-engine/src/rules/continuous-evaluator.ts', 'packages/game-engine/test/continuous-evaluator.test.ts'] },
    { id: 'bonds-endgame-and-scoring/end-condition-and-score-hooks', category: 'bonds-endgame-and-scoring', status: 'supported', summary: 'Rules Module 可提供可插拔終局條件與分數 contribution。', engineEvidence: ['packages/game-engine/src/rules/ruleset.ts', 'packages/game-engine/src/queries/scoring.ts', 'packages/game-engine/test/contracts.test.ts'] },
    { id: 'bonds-endgame-and-scoring/generic-bond-conditions', category: 'bonds-endgame-and-scoring', status: 'supported', summary: 'Rules Module 可用 JSON-only BondCondition（history、counter、玩家 zones、party、equipment、all/any/not）以明確 priority 評估羈絆；query 與 authoritative completion 共用純 evaluator。未載入正式或 provisional 羈絆卡條件。', engineEvidence: ['packages/game-protocol/src/bond.ts', 'packages/game-engine/src/rules/bond-condition-evaluator.ts', 'packages/game-engine/src/engine/dispatch.ts#maybeCompleteBonds', 'packages/game-engine/test/bond-condition-evaluator.test.ts'] },
    { id: 'bonds-endgame-and-scoring/vol1-ranking-and-hp', category: 'bonds-endgame-and-scoring', status: 'not-in-MVP-yet', summary: 'Vol.1 的 HP、排名、同分平均與多部位究極魔神計分。', engineEvidence: ['docs/10-第一擴充Vol1規則.md', 'packages/game-protocol/src/state.ts'], gapOrConstraint: '完整目標模型預留 counter/target 狀態，但 Vol.1 Rules Module 與排名 policy 不在基礎版 MVP 範圍。', recommendedNextStep: '等第一擴充啟用時，以獨立 Rules Module 和 scoring policy 實作。' }
  ]
};
