import type { CommandEnvelope, DomainEvent, EffectContext, GameState, PendingCommandContinuation } from '@guildmaster/game-protocol';
import { executeEffect, resumeEffectChoice, resumeEffectCounterConsent, validatePendingChoiceAgainstEffect, validatePendingCounterConsentAgainstEffect } from '../effects/executor.js';
import { combatRewardPoliciesFor } from '../rules/combat-reward-evaluator.js';
import { validateRulesetStateCompatibility, type Ruleset } from '../rules/ruleset.js';
type Result = { status: 'completed' | 'suspended' | 'failed' | 'unsupported'; events: DomainEvent[]; error?: string | undefined };
const same = (a: unknown, b: unknown) => JSON.stringify(a) === JSON.stringify(b);
const registry = (state: GameState, ruleset: Ruleset) => ({ rulesetVersion: state.rulesetVersion, modules: ruleset.modules.map(({ id, version }) => ({ id, version })) });
const executionId = (envelope: CommandEnvelope, ref: { moduleId: string; rewardPolicyId: string }) => `combat-reward:${envelope.commandId}:${ref.moduleId}:${ref.rewardPolicyId}`;
const maxResolutionEnvelopes = 256;
const appendEffectEvents = (events: DomainEvent[], incoming: readonly DomainEvent[], envelope: CommandEnvelope, policyIndex: number): void => { const start = events.length; events.push(...incoming.map((event, index) => ({ ...event, eventId: `combat-reward:${envelope.commandId}:${policyIndex}:effect:${start + index + 1}`, causedByCommandId: envelope.commandId }))); };
function save(state: GameState, envelope: CommandEnvelope, resolutionEnvelopes: readonly CommandEnvelope[], rollbackState: GameState, events: DomainEvent[], factStart: number, evaluation: import('@guildmaster/game-protocol').CombatRewardEvaluation, policyIndex: number, step: 'resume-policy-effect' | 'dispatch-next-policy', context: EffectContext): void { state.effectState.pendingCommand = { schemaVersion: 1, kind: 'combat-reward', continuationId: `combat-reward:${envelope.commandId}`, envelope: structuredClone(envelope), resolutionEnvelopes: structuredClone(resolutionEnvelopes), rollbackState: structuredClone(rollbackState), events: structuredClone(events), factStart, evaluation: structuredClone(evaluation), policyIndex, step, context: structuredClone(context), registry: registry(state, { modules: [] } as unknown as Ruleset) } as PendingCommandContinuation; (state.effectState.pendingCommand as Extract<PendingCommandContinuation, { kind: 'combat-reward' }>).registry = { rulesetVersion: state.rulesetVersion, modules: state.rulesModules.map(({ id, version }) => ({ id, version })) }; }
export function validatePendingCombatRewardContinuation(state: GameState, ruleset: Ruleset): string | undefined {
  const compatibilityError = validateRulesetStateCompatibility(state, ruleset);
  if (compatibilityError) return compatibilityError;
  const pending = state.effectState.pendingCommand;
  if (!pending || pending.kind !== 'combat-reward') return 'No pending combat reward continuation.';
  const choice = state.effectState.pendingChoice; const consent = state.effectState.pendingCounterConsent;
  const commandIds = [pending.envelope.commandId, ...pending.resolutionEnvelopes.map(({ commandId }) => commandId)];
  if (Boolean(choice) === Boolean(consent) || state.effectState.pendingLifecycle || state.effectState.pendingPostCommand || pending.envelope.command.type !== 'ATTACK_TARGET' || pending.continuationId !== `combat-reward:${pending.envelope.commandId}` || pending.envelope.gameId !== state.gameId || pending.envelope.expectedRevision !== state.revision || !same(pending.registry, registry(state, ruleset)) || pending.resolutionEnvelopes.length > maxResolutionEnvelopes || new Set(commandIds).size !== commandIds.length || pending.resolutionEnvelopes.some((resolution) => resolution.gameId !== state.gameId || resolution.expectedRevision !== pending.envelope.expectedRevision || (resolution.command.type !== 'RESOLVE_EFFECT_CHOICE' && resolution.command.type !== 'RESPOND_COUNTER_CONSENT' && resolution.command.type !== 'CANCEL_COUNTER_CONSENT' && resolution.command.type !== 'EXPIRE_COUNTER_CONSENT'))) return 'Malformed combat reward continuation.';
  if (pending.policyIndex < 0 || pending.policyIndex >= pending.evaluation.matchedPolicies.length || !same(pending.evaluation.registry, pending.registry) || pending.evaluation.input.targetId !== pending.envelope.command.targetId || pending.evaluation.input.playerId !== pending.envelope.actorId) return 'Combat reward cursor or evaluation mismatch.';
  if (pending.rollbackState.effectState.pendingChoice || pending.rollbackState.effectState.pendingCounterConsent || pending.rollbackState.effectState.pendingCommand || pending.rollbackState.effectState.pendingLifecycle || pending.rollbackState.effectState.pendingPostCommand) return 'Recursive combat reward rollback checkpoint.';
  const attackEvents = pending.events.filter(({ type }) => type === 'ATTACK_RESOLUTION_EVALUATED');
  if (attackEvents.length > 1) return 'Combat reward continuation has duplicate attack resolution evaluations.';
  const attackPayload = attackEvents[0]?.payload;
  if (attackPayload?.kind === 'attack-resolution') {
    const attack = attackPayload.evaluation;
    const target = state.enemyTargets[pending.envelope.command.targetId];
    const policy = ruleset.modules.find(({ id }) => id === attack.policy.moduleId)?.attackResolutionPolicies?.find(({ policyId }) => policyId === attack.policy.policyId);
    const expectedOutcome = attack.combat.outcome.kind === 'remove-target' ? 'removed' : 'defeated';
    if (!same(attack.input.registry, pending.registry) || !same(attack.combat.registry, pending.registry) || !same(attack.damage.input.registry, pending.registry) || attack.input.playerId !== pending.envelope.actorId || attack.input.targetId !== pending.envelope.command.targetId || !attack.damage.lethal || (attack.damage.input.lethalOutcome ?? 'defeated') !== expectedOutcome || !target || target.status !== expectedOutcome || target.health?.current !== 0 || !policy || policy.damage.amount !== attack.damage.input.requestedDamage || !same(policy.encounterPolicy, attack.damage.input.policy) || !same(policy.reasonCode, attack.reasonCode)) return 'Combat reward attack resolution is invalid or tampered.';
  } else if (attackPayload !== undefined) return 'Combat reward attack resolution payload is malformed.';
  const ref = pending.evaluation.matchedPolicies[pending.policyIndex]!;
  const suspension = choice ?? consent;
  if (suspension!.executionId !== executionId(pending.envelope, ref) || !same(suspension!.context, pending.context)) return 'Combat reward suspension does not match the current policy.';
  const policy = combatRewardPoliciesFor(ruleset, pending.evaluation)[pending.policyIndex];
  if (!policy) return 'Combat reward policy is no longer registered.';
  return choice ? validatePendingChoiceAgainstEffect(choice, policy.reward, state, ruleset) : validatePendingCounterConsentAgainstEffect(consent!, policy.reward);
}
export function beginCombatRewardPipeline(state: GameState, ruleset: Ruleset, envelope: CommandEnvelope, rollbackState: GameState, events: DomainEvent[], factStart: number, evaluation: import('@guildmaster/game-protocol').CombatRewardEvaluation, context: EffectContext): Result { return continueCombatRewardPipeline(state, ruleset, envelope, [], rollbackState, events, factStart, evaluation, 0, context); }
export function continueCombatRewardPipeline(state: GameState, ruleset: Ruleset, envelope: CommandEnvelope, resolutionEnvelopes: readonly CommandEnvelope[], rollbackState: GameState, events: DomainEvent[], factStart: number, evaluation: import('@guildmaster/game-protocol').CombatRewardEvaluation, start: number, context: EffectContext): Result { const policies = combatRewardPoliciesFor(ruleset, evaluation); if (policies.length !== evaluation.matchedPolicies.length) return { status: 'failed', events: [], error: 'Unknown combat reward policy.' }; for (let index = start; index < policies.length; index += 1) { const policy = policies[index]!; const result = executeEffect(state, ruleset, policy.reward, context, executionId(envelope, policy)); appendEffectEvents(events, result.events, envelope, index); if (result.status === 'suspended') { save(state, envelope, resolutionEnvelopes, rollbackState, events, factStart, evaluation, index, 'resume-policy-effect', state.effectState.pendingChoice?.context ?? state.effectState.pendingCounterConsent?.context ?? context); return { status: 'suspended', events }; } if (result.status !== 'completed') return { status: result.status, events: [], error: result.error }; events.push({ eventId: `combat-reward:${envelope.commandId}:${index}`, revision: state.revision + 1, type: 'COMBAT_REWARD_POLICY_EXECUTED', message: `Executed combat reward policy ${policy.rewardPolicyId}.`, causedByCommandId: envelope.commandId, payload: { schemaVersion: 1, kind: 'combat-reward-evaluation', evaluation: structuredClone(evaluation), executedPolicy: { moduleId: policy.moduleId, rewardPolicyId: policy.rewardPolicyId } } }); } return { status: 'completed', events }; }
export function resumeCombatRewardPipeline(state: GameState, ruleset: Ruleset, resolutionEnvelope: CommandEnvelope): Result { const error = validatePendingCombatRewardContinuation(state, ruleset); const pending = state.effectState.pendingCommand; if (error || !pending || pending.kind !== 'combat-reward') return { status: 'failed', events: [], error: error }; const command = resolutionEnvelope.command; if (command.type !== 'RESOLVE_EFFECT_CHOICE' || resolutionEnvelope.actorId !== pending.envelope.actorId) return { status: 'failed', events: [], error: 'Wrong combat reward choice actor or command.' }; const result = resumeEffectChoice(state, ruleset, resolutionEnvelope.actorId, command.executionId, command.choiceId, command.optionId); const events = [...pending.events]; appendEffectEvents(events, result.events, pending.envelope, pending.policyIndex); const resolutionEnvelopes = [...pending.resolutionEnvelopes, structuredClone(resolutionEnvelope)]; if (result.status === 'suspended') { save(state, pending.envelope, resolutionEnvelopes, pending.rollbackState, events, pending.factStart, pending.evaluation, pending.policyIndex, 'resume-policy-effect', state.effectState.pendingChoice?.context ?? state.effectState.pendingCounterConsent?.context ?? pending.context); return { status: 'suspended', events }; } if (result.status !== 'completed') return { status: result.status, events: [], error: result.error }; const policy = combatRewardPoliciesFor(ruleset, pending.evaluation)[pending.policyIndex]!; events.push({ eventId: `combat-reward:${pending.envelope.commandId}:${pending.policyIndex}`, revision: state.revision + 1, type: 'COMBAT_REWARD_POLICY_EXECUTED', message: `Executed combat reward policy ${policy.rewardPolicyId}.`, causedByCommandId: pending.envelope.commandId, payload: { schemaVersion: 1, kind: 'combat-reward-evaluation', evaluation: structuredClone(pending.evaluation), executedPolicy: { moduleId: policy.moduleId, rewardPolicyId: policy.rewardPolicyId } } }); delete state.effectState.pendingCommand; return continueCombatRewardPipeline(state, ruleset, pending.envelope, resolutionEnvelopes, pending.rollbackState, events, pending.factStart, pending.evaluation, pending.policyIndex + 1, pending.context); }
export function resumeCombatRewardCounterConsent(state: GameState, ruleset: Ruleset, resolutionEnvelope: CommandEnvelope, action: 'accept' | 'decline' | 'cancel' | 'expire'): Result { const error = validatePendingCombatRewardContinuation(state, ruleset); const pending = state.effectState.pendingCommand; if (error || !pending || pending.kind !== 'combat-reward') return { status: 'failed', events: [], error }; const command = resolutionEnvelope.command; if (command.type !== 'RESPOND_COUNTER_CONSENT' && command.type !== 'CANCEL_COUNTER_CONSENT' && command.type !== 'EXPIRE_COUNTER_CONSENT') return { status: 'failed', events: [], error: 'Wrong combat reward counter consent command.' }; const result = resumeEffectCounterConsent(state, ruleset, resolutionEnvelope.actorId, command.requestId, action); const events = [...pending.events]; appendEffectEvents(events, result.events, pending.envelope, pending.policyIndex); const resolutionEnvelopes = [...pending.resolutionEnvelopes, structuredClone(resolutionEnvelope)]; if (result.status === 'suspended') { save(state, pending.envelope, resolutionEnvelopes, pending.rollbackState, events, pending.factStart, pending.evaluation, pending.policyIndex, 'resume-policy-effect', pending.context); return { status: 'suspended', events }; } if (result.status !== 'completed') return { status: result.status, events: [], error: result.error }; const policy = combatRewardPoliciesFor(ruleset, pending.evaluation)[pending.policyIndex]!; events.push({ eventId: `combat-reward:${pending.envelope.commandId}:${pending.policyIndex}`, revision: state.revision + 1, type: 'COMBAT_REWARD_POLICY_EXECUTED', message: `Executed combat reward policy ${policy.rewardPolicyId}.`, causedByCommandId: pending.envelope.commandId, payload: { schemaVersion: 1, kind: 'combat-reward-evaluation', evaluation: structuredClone(pending.evaluation), executedPolicy: { moduleId: policy.moduleId, rewardPolicyId: policy.rewardPolicyId } } }); delete state.effectState.pendingCommand; return continueCombatRewardPipeline(state, ruleset, pending.envelope, resolutionEnvelopes, pending.rollbackState, events, pending.factStart, pending.evaluation, pending.policyIndex + 1, pending.context); }
