import type { CommandEnvelope, DomainEvent, EffectContext, GameState, PendingCommandContinuation } from '@guildmaster/game-protocol';
import { executeEffect, resumeEffectChoice, resumeEffectCounterConsent, validatePendingChoiceAgainstEffect, validatePendingCounterConsentAgainstEffect } from '../effects/executor.js';
import { combatRewardPoliciesFor } from '../rules/combat-reward-evaluator.js';
import { validateRulesetStateCompatibility, type Ruleset } from '../rules/ruleset.js';
type Result = { status: 'completed' | 'suspended' | 'failed' | 'unsupported'; events: DomainEvent[]; error?: string | undefined };
const same = (a: unknown, b: unknown) => JSON.stringify(a) === JSON.stringify(b);
const registry = (state: GameState, ruleset: Ruleset) => ({ rulesetVersion: state.rulesetVersion, modules: ruleset.modules.map(({ id, version }) => ({ id, version })) });
const executionId = (envelope: CommandEnvelope, ref: { moduleId: string; rewardPolicyId: string }) => `combat-reward:${envelope.commandId}:${ref.moduleId}:${ref.rewardPolicyId}`;
const appendEffectEvents = (events: DomainEvent[], incoming: readonly DomainEvent[], envelope: CommandEnvelope, policyIndex: number): void => { const start = events.length; events.push(...incoming.map((event, index) => ({ ...event, eventId: `combat-reward:${envelope.commandId}:${policyIndex}:effect:${start + index + 1}` }))); };
function save(state: GameState, envelope: CommandEnvelope, rollbackState: GameState, events: DomainEvent[], factStart: number, evaluation: import('@guildmaster/game-protocol').CombatRewardEvaluation, policyIndex: number, step: 'resume-policy-effect' | 'dispatch-next-policy', context: EffectContext): void { state.effectState.pendingCommand = { schemaVersion: 1, kind: 'combat-reward', continuationId: `combat-reward:${envelope.commandId}`, envelope: structuredClone(envelope), rollbackState: structuredClone(rollbackState), events: structuredClone(events), factStart, evaluation: structuredClone(evaluation), policyIndex, step, context: structuredClone(context), registry: registry(state, { modules: [] } as unknown as Ruleset) } as PendingCommandContinuation; (state.effectState.pendingCommand as Extract<PendingCommandContinuation, { kind: 'combat-reward' }>).registry = { rulesetVersion: state.rulesetVersion, modules: state.rulesModules.map(({ id, version }) => ({ id, version })) }; }
export function validatePendingCombatRewardContinuation(state: GameState, ruleset: Ruleset): string | undefined {
  const compatibilityError = validateRulesetStateCompatibility(state, ruleset);
  if (compatibilityError) return compatibilityError;
  const pending = state.effectState.pendingCommand;
  if (!pending || pending.kind !== 'combat-reward') return 'No pending combat reward continuation.';
  const choice = state.effectState.pendingChoice; const consent = state.effectState.pendingCounterConsent;
  if (Boolean(choice) === Boolean(consent) || state.effectState.pendingLifecycle || state.effectState.pendingPostCommand || pending.envelope.command.type !== 'ATTACK_TARGET' || pending.continuationId !== `combat-reward:${pending.envelope.commandId}` || pending.envelope.gameId !== state.gameId || pending.envelope.expectedRevision !== state.revision || !same(pending.registry, registry(state, ruleset))) return 'Malformed combat reward continuation.';
  if (pending.policyIndex < 0 || pending.policyIndex >= pending.evaluation.matchedPolicies.length || !same(pending.evaluation.registry, pending.registry) || pending.evaluation.input.targetId !== pending.envelope.command.targetId || pending.evaluation.input.playerId !== pending.envelope.actorId) return 'Combat reward cursor or evaluation mismatch.';
  if (pending.rollbackState.effectState.pendingChoice || pending.rollbackState.effectState.pendingCounterConsent || pending.rollbackState.effectState.pendingCommand || pending.rollbackState.effectState.pendingLifecycle || pending.rollbackState.effectState.pendingPostCommand) return 'Recursive combat reward rollback checkpoint.';
  const ref = pending.evaluation.matchedPolicies[pending.policyIndex]!;
  const suspension = choice ?? consent;
  if (suspension!.executionId !== executionId(pending.envelope, ref) || !same(suspension!.context, pending.context)) return 'Combat reward suspension does not match the current policy.';
  const policy = combatRewardPoliciesFor(ruleset, pending.evaluation)[pending.policyIndex];
  if (!policy) return 'Combat reward policy is no longer registered.';
  return choice ? validatePendingChoiceAgainstEffect(choice, policy.reward) : validatePendingCounterConsentAgainstEffect(consent!, policy.reward);
}
export function beginCombatRewardPipeline(state: GameState, ruleset: Ruleset, envelope: CommandEnvelope, rollbackState: GameState, events: DomainEvent[], factStart: number, evaluation: import('@guildmaster/game-protocol').CombatRewardEvaluation, context: EffectContext): Result { return continueCombatRewardPipeline(state, ruleset, envelope, rollbackState, events, factStart, evaluation, 0, context); }
export function continueCombatRewardPipeline(state: GameState, ruleset: Ruleset, envelope: CommandEnvelope, rollbackState: GameState, events: DomainEvent[], factStart: number, evaluation: import('@guildmaster/game-protocol').CombatRewardEvaluation, start: number, context: EffectContext): Result { const policies = combatRewardPoliciesFor(ruleset, evaluation); if (policies.length !== evaluation.matchedPolicies.length) return { status: 'failed', events: [], error: 'Unknown combat reward policy.' }; for (let index = start; index < policies.length; index += 1) { const policy = policies[index]!; const result = executeEffect(state, ruleset, policy.reward, context, executionId(envelope, policy)); appendEffectEvents(events, result.events, envelope, index); if (result.status === 'suspended') { save(state, envelope, rollbackState, events, factStart, evaluation, index, 'resume-policy-effect', context); return { status: 'suspended', events }; } if (result.status !== 'completed') return { status: result.status, events: [], error: result.error }; events.push({ eventId: `combat-reward:${envelope.commandId}:${index}`, revision: state.revision + 1, type: 'COMBAT_REWARD_POLICY_EXECUTED', message: `Executed combat reward policy ${policy.rewardPolicyId}.`, causedByCommandId: envelope.commandId, payload: { schemaVersion: 1, kind: 'combat-reward-evaluation', evaluation: structuredClone(evaluation), executedPolicy: { moduleId: policy.moduleId, rewardPolicyId: policy.rewardPolicyId } } }); } return { status: 'completed', events }; }
export function resumeCombatRewardPipeline(state: GameState, ruleset: Ruleset, actorId: string, execution: string, choice: string, option: string): Result { const error = validatePendingCombatRewardContinuation(state, ruleset); const pending = state.effectState.pendingCommand; if (error || !pending || pending.kind !== 'combat-reward') return { status: 'failed', events: [], error: error }; if (actorId !== pending.envelope.actorId) return { status: 'failed', events: [], error: 'Wrong combat reward choice actor.' }; const result = resumeEffectChoice(state, ruleset, actorId, execution, choice, option); const events = [...pending.events]; appendEffectEvents(events, result.events, pending.envelope, pending.policyIndex); if (result.status === 'suspended') { save(state, pending.envelope, pending.rollbackState, events, pending.factStart, pending.evaluation, pending.policyIndex, 'resume-policy-effect', pending.context); return { status: 'suspended', events }; } if (result.status !== 'completed') return { status: result.status, events: [], error: result.error }; const policy = combatRewardPoliciesFor(ruleset, pending.evaluation)[pending.policyIndex]!; events.push({ eventId: `combat-reward:${pending.envelope.commandId}:${pending.policyIndex}`, revision: state.revision + 1, type: 'COMBAT_REWARD_POLICY_EXECUTED', message: `Executed combat reward policy ${policy.rewardPolicyId}.`, causedByCommandId: pending.envelope.commandId, payload: { schemaVersion: 1, kind: 'combat-reward-evaluation', evaluation: structuredClone(pending.evaluation), executedPolicy: { moduleId: policy.moduleId, rewardPolicyId: policy.rewardPolicyId } } }); delete state.effectState.pendingCommand; return continueCombatRewardPipeline(state, ruleset, pending.envelope, pending.rollbackState, events, pending.factStart, pending.evaluation, pending.policyIndex + 1, pending.context); }
export function resumeCombatRewardCounterConsent(state: GameState, ruleset: Ruleset, actorId: string, requestId: string, action: 'accept' | 'decline' | 'cancel' | 'expire'): Result { const error = validatePendingCombatRewardContinuation(state, ruleset); const pending = state.effectState.pendingCommand; if (error || !pending || pending.kind !== 'combat-reward') return { status: 'failed', events: [], error }; const result = resumeEffectCounterConsent(state, ruleset, actorId, requestId, action); const events = [...pending.events]; appendEffectEvents(events, result.events, pending.envelope, pending.policyIndex); if (result.status === 'suspended') { save(state, pending.envelope, pending.rollbackState, events, pending.factStart, pending.evaluation, pending.policyIndex, 'resume-policy-effect', pending.context); return { status: 'suspended', events }; } if (result.status !== 'completed') return { status: result.status, events: [], error: result.error }; const policy = combatRewardPoliciesFor(ruleset, pending.evaluation)[pending.policyIndex]!; events.push({ eventId: `combat-reward:${pending.envelope.commandId}:${pending.policyIndex}`, revision: state.revision + 1, type: 'COMBAT_REWARD_POLICY_EXECUTED', message: `Executed combat reward policy ${policy.rewardPolicyId}.`, causedByCommandId: pending.envelope.commandId, payload: { schemaVersion: 1, kind: 'combat-reward-evaluation', evaluation: structuredClone(pending.evaluation), executedPolicy: { moduleId: policy.moduleId, rewardPolicyId: policy.rewardPolicyId } } }); delete state.effectState.pendingCommand; return continueCombatRewardPipeline(state, ruleset, pending.envelope, pending.rollbackState, events, pending.factStart, pending.evaluation, pending.policyIndex + 1, pending.context); }
