import { z } from 'zod';
import type { GameState } from './state.js';
const jsonValue: z.ZodType<unknown> = z.lazy(() => z.union([z.string(), z.number(), z.boolean(), z.null(), z.array(jsonValue), z.record(jsonValue)]));
const manifest = z.object({ id: z.string(), version: z.string(), hash: z.string() });
const pendingChoice = z.object({ schemaVersion: z.literal(1), executionId: z.string(), choiceId: z.string(), actorId: z.string(), options: z.array(z.object({ id: z.string(), effect: jsonValue })), remaining: z.array(jsonValue), context: z.object({ controllerId: z.string(), cardRefs: z.record(z.string()).optional(), playerRefs: z.record(z.string()).optional() }) });
const lifecyclePayload = z.object({ schemaVersion: z.literal(1), point: z.enum(['game-setup', 'game-start', 'turn-start', 'turn-end', 'phase-start', 'phase-end', 'command-before', 'command-after', 'event-before', 'event-after', 'game-end-evaluation']), actorId: z.string().optional(), commandType: z.string().optional(), eventType: z.string().optional(), phase: z.string().optional(), metadata: z.record(z.union([z.string(), z.number(), z.boolean(), z.null()])).optional() });
const lifecycleHookRef = z.object({ moduleId: z.string(), hookId: z.string() });
const pendingLifecycle = z.object({ schemaVersion: z.literal(1), dispatchId: z.string(), payload: lifecyclePayload, context: z.object({ controllerId: z.string(), cardRefs: z.record(z.string()).optional(), playerRefs: z.record(z.string()).optional() }), currentHook: lifecycleHookRef, remainingHooks: z.array(lifecycleHookRef), registry: z.object({ rulesetVersion: z.string(), modules: z.array(z.object({ id: z.string(), version: z.string() })) }), rollbackState: jsonValue });
const pendingCommand = z.object({ schemaVersion: z.literal(1), envelope: z.object({ protocolVersion: z.literal(1), gameId: z.string(), commandId: z.string(), actorId: z.string(), expectedRevision: z.number(), command: jsonValue }) });
export const GameStateSchema = z.object({
  schemaVersion: z.literal(2), engineVersion: z.string(), rulesetVersion: z.string(), contentPacks: z.array(manifest), rulesModules: z.array(z.object({ id: z.string(), version: z.string(), config: z.record(jsonValue).optional() })), gameId: z.string(), seed: z.number(), rngState: z.number(), revision: z.number(), status: z.enum(['playing', 'finalRound', 'finished', 'pendingOfficialRuling']),
  players: z.array(z.object({ id: z.string(), name: z.string(), kind: z.enum(['human', 'ai']), drawPile: z.array(z.string()), hand: z.array(z.string()), discardPile: z.array(z.string()), party: z.array(z.object({ adventurerId: z.string(), equipmentId: z.string().optional() })), playArea: z.array(z.string()), bonds: z.array(z.object({ bondId: z.string(), completed: z.boolean() })), counters: z.array(z.object({ resourceId: z.string(), amount: z.number(), visibility: z.enum(['public', 'ownerOnly', 'allPlayersByConsent']), sourceRefs: z.array(z.string()).optional() })), moduleState: z.record(jsonValue), turnPurchaseBonus: z.number(), turnPurchaseSpent: z.number(), turnCombatBonus: z.number(), history: z.object({ defeatedBosses: z.number(), defeatedMonsters: z.number() }) })),
  activePlayerId: z.string(), startingPlayerId: z.string(), round: z.number(), phase: z.enum(['action1', 'combat', 'action2', 'purchase', 'rest']), cards: z.record(z.object({ id: z.string(), definitionId: z.string(), ownerId: z.string().optional(), state: z.record(jsonValue).optional() })), zones: z.record(z.object({ zoneId: z.string(), kind: z.enum(['orderedDeck', 'faceUpRow', 'singleSlot', 'moduleArea']), cardIds: z.array(z.string()), visibility: z.enum(['public', 'ownerOnly']), ownerId: z.string().optional(), rulesModuleId: z.string().optional(), metadata: z.record(jsonValue).optional() })), enemyTargets: z.record(z.object({ targetId: z.string(), cardInstanceId: z.string(), kind: z.string(), status: z.enum(['available', 'engaged', 'defeated', 'removed']), parentEncounterId: z.string().optional(), partKey: z.string().optional(), zoneId: z.string().optional(), health: z.object({ current: z.number(), max: z.number() }).optional(), attachments: z.array(z.string()), moduleState: z.record(jsonValue) })), enemyEncounters: z.array(z.object({ encounterId: z.string(), targetIds: z.array(z.string()), kind: z.string(), status: z.enum(['active', 'finished']), rulesModuleId: z.string().optional(), state: z.record(jsonValue) })), removedCards: z.array(z.string()), moduleState: z.record(jsonValue), effectState: z.object({ pendingChoice: pendingChoice.optional(), pendingLifecycle: pendingLifecycle.optional(), pendingCommand: pendingCommand.optional() }).optional(), endState: z.object({ conditionId: z.string(), finalRoundEndPlayerId: z.string(), triggeredAtRevision: z.number() }).optional(), eventLogCursor: z.number()
});
export type VersionedSnapshot = { schemaVersion: 2; engineVersion: string; rulesetVersion: string; contentPacks: GameState['contentPacks']; rulesModules: GameState['rulesModules']; state: GameState };
export const SnapshotEnvelopeSchema = z.object({ schemaVersion: z.literal(2), engineVersion: z.string(), rulesetVersion: z.string(), contentPacks: z.array(manifest), rulesModules: z.array(z.object({ id: z.string(), version: z.string(), config: z.record(jsonValue).optional() })), state: GameStateSchema });
