import { z } from 'zod';
import type { GameState } from './state.js';
import { CombatEvaluationSchema } from './combat.js';
import { CommandEnvelopeSchema } from './commands.js';
import { EffectNodeSchema } from './effects.js';
import { EncounterEventPayloadSchema } from './encounter.js';
const jsonValue: z.ZodType<unknown> = z.lazy(() => z.union([z.string(), z.number().finite(), z.boolean(), z.null(), z.array(jsonValue), z.record(jsonValue)]));
const manifest = z.object({ id: z.string(), version: z.string(), hash: z.string() });
const pendingChoice = z.object({ schemaVersion: z.literal(1), executionId: z.string(), choiceId: z.string(), actorId: z.string(), options: z.array(z.object({ id: z.string(), effect: EffectNodeSchema })), remaining: z.array(EffectNodeSchema), context: z.object({ controllerId: z.string(), cardRefs: z.record(z.string()).optional(), playerRefs: z.record(z.string()).optional() }) });
const lifecyclePayload = z.object({ schemaVersion: z.literal(1), point: z.enum(['game-setup', 'game-start', 'turn-start', 'turn-end', 'phase-start', 'phase-end', 'command-before', 'command-after', 'event-before', 'event-after', 'game-end-evaluation']), actorId: z.string().optional(), commandType: z.string().optional(), eventType: z.string().optional(), phase: z.string().optional(), metadata: z.record(z.union([z.string(), z.number().finite(), z.boolean(), z.null()])).optional() });
const lifecycleHookRef = z.object({ moduleId: z.string(), hookId: z.string() });
const pendingLifecycle = z.object({ schemaVersion: z.literal(1), dispatchId: z.string(), payload: lifecyclePayload, context: z.object({ controllerId: z.string(), cardRefs: z.record(z.string()).optional(), playerRefs: z.record(z.string()).optional() }), currentHook: lifecycleHookRef, remainingHooks: z.array(lifecycleHookRef), registry: z.object({ rulesetVersion: z.string(), modules: z.array(z.object({ id: z.string(), version: z.string() })) }), rollbackState: jsonValue });
const combatEventPayload = z.object({ schemaVersion: z.literal(1), kind: z.literal('combat-evaluation'), evaluation: CombatEvaluationSchema }).strict();
const combatRewardEventPayload = z.object({ schemaVersion: z.literal(1), kind: z.literal('combat-reward-evaluation'), evaluation: jsonValue, executedPolicy: z.object({ moduleId: z.string().min(1), rewardPolicyId: z.string().min(1) }).strict() }).strict();
const overflowEventPayload = z.object({ schemaVersion: z.literal(1), kind: z.literal('team-overflow'), policy: z.object({ moduleId: z.string(), policyId: z.string() }).optional(), candidateIds: z.array(z.string()).min(1) }).strict();
const domainEvent = z.object({ eventId: z.string(), revision: z.number().finite().int().nonnegative(), type: z.string(), message: z.string(), causedByCommandId: z.string().optional(), moduleId: z.string().optional(), payload: z.union([combatEventPayload, combatRewardEventPayload, overflowEventPayload, EncounterEventPayloadSchema]).optional() }).superRefine((value, context) => {
  if (value.type === 'COMBAT_EVALUATED' && value.payload?.kind !== 'combat-evaluation') context.addIssue({ code: z.ZodIssueCode.custom, path: ['payload'], message: 'COMBAT_EVALUATED requires a combat-evaluation payload.' });
  if (value.type !== 'COMBAT_EVALUATED' && value.payload?.kind === 'combat-evaluation') context.addIssue({ code: z.ZodIssueCode.custom, path: ['payload'], message: 'combat-evaluation payload requires COMBAT_EVALUATED event type.' });
  const encounterTypes = new Set(['ENCOUNTER_CREATED', 'ENEMY_TARGET_CREATED', 'ENEMY_ATTACHMENT_ADDED', 'ENEMY_TARGET_DAMAGED', 'ENEMY_TARGET_DEFEATED', 'ENEMY_TARGET_REMOVED', 'ENCOUNTER_COMPLETED']);
  if (encounterTypes.has(value.type) && value.payload?.kind !== 'encounter-resolution') context.addIssue({ code: z.ZodIssueCode.custom, path: ['payload'], message: 'Encounter event requires an encounter-resolution payload.' });
  if (!encounterTypes.has(value.type) && value.payload?.kind === 'encounter-resolution') context.addIssue({ code: z.ZodIssueCode.custom, path: ['payload'], message: 'encounter-resolution payload requires an encounter event type.' });
});
const pendingCommand = z.union([
  z.object({ schemaVersion: z.literal(1), kind: z.literal('command-before-lifecycle').optional(), envelope: CommandEnvelopeSchema, events: z.array(domainEvent).default([]) }),
  z.object({ schemaVersion: z.literal(1), kind: z.literal('team-overflow'), envelope: CommandEnvelopeSchema, events: z.array(domainEvent).default([]), rollbackState: jsonValue, policy: z.object({ moduleId: z.string(), policyId: z.string() }), candidateIds: z.array(z.string()).min(1), requiredSelectionCount: z.number().int().positive(), optionCandidates: z.record(z.array(z.string()).min(1)), registry: z.object({ rulesetVersion: z.string(), modules: z.array(z.object({ id: z.string(), version: z.string() })) }) }),
  z.object({ schemaVersion: z.literal(1), kind: z.literal('combat-reward'), continuationId: z.string(), envelope: CommandEnvelopeSchema, rollbackState: jsonValue, events: z.array(domainEvent), factStart: z.number().int().nonnegative(), evaluation: jsonValue, policyIndex: z.number().int().nonnegative(), step: z.enum(['resume-policy-effect', 'dispatch-next-policy']), context: z.object({ controllerId: z.string(), cardRefs: z.record(z.string()).optional(), playerRefs: z.record(z.string()).optional() }), registry: z.object({ rulesetVersion: z.string(), modules: z.array(z.object({ id: z.string(), version: z.string() })) }) })
]);
const pendingPostCommand = z.object({ schemaVersion: z.literal(1), continuationId: z.string(), envelope: CommandEnvelopeSchema, rollbackState: jsonValue, facts: z.array(domainEvent), factIndex: z.number().int().nonnegative(), boundary: z.enum(['event-before', 'event-after', 'command-after']), step: z.enum(['dispatch-boundary', 'resume-boundary']), events: z.array(domainEvent), payload: lifecyclePayload, context: z.object({ controllerId: z.string(), cardRefs: z.record(z.string()).optional(), playerRefs: z.record(z.string()).optional() }), registry: z.object({ rulesetVersion: z.string(), modules: z.array(z.object({ id: z.string(), version: z.string() })) }) });
export const GameStateSchema = z.object({
  schemaVersion: z.literal(2), engineVersion: z.string(), rulesetVersion: z.string(), contentPacks: z.array(manifest), rulesModules: z.array(z.object({ id: z.string(), version: z.string(), config: z.record(jsonValue).optional() })), gameId: z.string(), seed: z.number().finite().int(), rngState: z.number().finite().int().nonnegative(), revision: z.number().finite().int().nonnegative(), status: z.enum(['playing', 'finalRound', 'finished', 'pendingOfficialRuling']),
  players: z.array(z.object({ id: z.string(), name: z.string(), kind: z.enum(['human', 'ai']), drawPile: z.array(z.string()), hand: z.array(z.string()), discardPile: z.array(z.string()), party: z.array(z.object({ adventurerId: z.string(), equipmentId: z.string().optional() })), playArea: z.array(z.string()), bonds: z.array(z.object({ bondId: z.string(), completed: z.boolean() })), counters: z.array(z.object({ resourceId: z.string(), amount: z.number().finite(), visibility: z.enum(['public', 'ownerOnly', 'allPlayersByConsent']), sourceRefs: z.array(z.string()).optional() })), moduleState: z.record(jsonValue), turnPurchaseBonus: z.number().finite(), turnPurchaseSpent: z.number().finite().nonnegative(), turnCombatBonus: z.number().finite(), history: z.object({ defeatedBosses: z.number().finite().int().nonnegative(), defeatedMonsters: z.number().finite().int().nonnegative() }) })),
  activePlayerId: z.string(), startingPlayerId: z.string(), round: z.number().finite().int().positive(), phase: z.enum(['action1', 'combat', 'action2', 'purchase', 'rest']), cards: z.record(z.object({ id: z.string(), definitionId: z.string(), ownerId: z.string().optional(), state: z.record(jsonValue).optional() })), zones: z.record(z.object({ zoneId: z.string(), kind: z.enum(['orderedDeck', 'faceUpRow', 'singleSlot', 'moduleArea']), cardIds: z.array(z.string()), visibility: z.enum(['public', 'ownerOnly']), ownerId: z.string().optional(), rulesModuleId: z.string().optional(), metadata: z.record(jsonValue).optional() })), enemyTargets: z.record(z.object({ targetId: z.string(), cardInstanceId: z.string(), kind: z.string(), status: z.enum(['available', 'engaged', 'defeated', 'removed']), parentEncounterId: z.string().optional(), partKey: z.string().optional(), zoneId: z.string().optional(), health: z.object({ current: z.number().finite().int().nonnegative(), max: z.number().finite().int().nonnegative() }).refine((value) => value.current <= value.max).optional(), attachments: z.array(z.string()), moduleState: z.record(jsonValue) })), enemyEncounters: z.array(z.object({ encounterId: z.string(), targetIds: z.array(z.string()), kind: z.string(), status: z.enum(['active', 'finished']), rulesModuleId: z.string().optional(), resolutionPolicy: z.object({ moduleId: z.string(), policyId: z.string() }).optional(), state: z.record(jsonValue) })), removedCards: z.array(z.string()), moduleState: z.record(jsonValue), effectState: z.object({ pendingChoice: pendingChoice.optional(), pendingLifecycle: pendingLifecycle.optional(), pendingCommand: pendingCommand.optional(), pendingPostCommand: pendingPostCommand.optional() }).optional(), endState: z.object({ conditionId: z.string(), finalRoundEndPlayerId: z.string(), triggeredAtRevision: z.number() }).optional(), eventLogCursor: z.number().finite().int().nonnegative()
});
export type VersionedSnapshot = { schemaVersion: 2; engineVersion: string; rulesetVersion: string; contentPacks: GameState['contentPacks']; rulesModules: GameState['rulesModules']; state: GameState };
export const SnapshotEnvelopeSchema = z.object({ schemaVersion: z.literal(2), engineVersion: z.string(), rulesetVersion: z.string(), contentPacks: z.array(manifest), rulesModules: z.array(z.object({ id: z.string(), version: z.string(), config: z.record(jsonValue).optional() })), state: GameStateSchema });
