import { z } from 'zod';
export type SupplyRowConfiguration = { schemaVersion: 1; configurationId: string; moduleId: string; priority?: number; supply: string; sourceDeckZoneId: string; targetRowZoneId: string; targetSize: number; mode: 'refill-to-target' };
export type SupplyRowEvaluation = { schemaVersion: 1; status: 'no-refill-needed' | 'refill-required' | 'partially-refillable'; configuration: { moduleId: string; configurationId: string }; sourceDeckZoneId: string; targetRowZoneId: string; requestedDrawCount: number; actualDrawCount: number; sourceCount: number; rowCount: number; depleted: boolean; registry: { rulesetVersion: string; modules: readonly { id: string; version: string }[] } };
const canonicalId = z.string().min(1).refine((value) => value === value.trim(), 'Value must not have leading or trailing whitespace.');
export const SupplyRowConfigurationSchema = z.object({ schemaVersion: z.literal(1), configurationId: canonicalId, moduleId: canonicalId, priority: z.number().finite().optional(), supply: canonicalId, sourceDeckZoneId: canonicalId, targetRowZoneId: canonicalId, targetSize: z.number().int().nonnegative(), mode: z.literal('refill-to-target') }).strict();
export function validateSupplyRowConfiguration(value: SupplyRowConfiguration, moduleId: string): string[] { const parsed = SupplyRowConfigurationSchema.safeParse(value); const errors = parsed.success ? [] : parsed.error.issues.map((x) => `Supply row configuration has invalid data at ${x.path.join('.')}: ${x.message}`); if (parsed.success && parsed.data.moduleId !== moduleId) errors.push(`Supply row configuration ${parsed.data.configurationId} must belong to module ${moduleId}.`); if (parsed.success && parsed.data.sourceDeckZoneId === parsed.data.targetRowZoneId) errors.push('Supply row source and target must differ.'); return errors; }
export type SupplyRowRefreshPolicy = { schemaVersion: 1; refreshPolicyId: string; moduleId: string; priority?: number; supplyRowConfigurationId: string; destinationZoneId: string; ordering: 'preserve-top' | 'preserve-bottom' | 'reverse-top' | 'reverse-bottom'; refill: boolean; reasonCode: string };
export type SupplyRowRefreshEvaluation = { schemaVersion: 1; status: 'ready' | 'no-op'; policy: { moduleId: string; refreshPolicyId: string }; configuration: { moduleId: string; configurationId: string }; rowCardIds: readonly string[]; sourceDeckZoneId: string; targetRowZoneId: string; destinationZoneId: string; requestedRefillCount: number; actualRefillCount: number; registry: SupplyRowEvaluation['registry'] };
export const SupplyRowRefreshPolicySchema = z.object({ schemaVersion: z.literal(1), refreshPolicyId: z.string().trim().min(1), moduleId: z.string().trim().min(1), priority: z.number().finite().optional(), supplyRowConfigurationId: z.string().trim().min(1), destinationZoneId: z.string().trim().min(1), ordering: z.enum(['preserve-top', 'preserve-bottom', 'reverse-top', 'reverse-bottom']), refill: z.boolean(), reasonCode: z.string().trim().min(1) }).strict();
export function validateSupplyRowRefreshPolicy(value: SupplyRowRefreshPolicy, moduleId: string): string[] { const parsed = SupplyRowRefreshPolicySchema.safeParse(value); const errors = parsed.success ? [] : parsed.error.issues.map((x) => `Supply row refresh policy has invalid data at ${x.path.join('.')}: ${x.message}`); if (parsed.success && parsed.data.moduleId !== moduleId) errors.push(`Supply row refresh policy ${parsed.data.refreshPolicyId} must belong to module ${moduleId}.`); return errors; }
